import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "1.0.0" // up-to-date

    /**
     * [cardview website](http://developer.android.com/tools/extras/support-library.html) */
    const val cardview: String = "1.0.0" // up-to-date

    /**
     * [core-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val androidx_core: String = "1.0.0" // up-to-date

    /**
     * [recyclerview website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview: String = "1.0.0" // up-to-date

    const val com_afollestad_material_dialogs_core: String =
            "0.9.6.0" // available milestone: "2.0.0-beta4" 

    /**
     * [constraint-layout website](http://tools.android.com) */
    const val constraint_layout: String = "1.1.3" // available milestone: "2.0.0-alpha2" 

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String =
            "3.2.0-beta01-4818971" // available milestone: "3.4.0-alpha02-5013011" 

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "3.2.0-beta01" // available milestone: "3.4.0-alpha02" 

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "26.2.0-beta01" // available milestone: "26.4.0-alpha02" 

    /**
     * [material-design-dimens website](https://github.com/DmitryMalkovich/material-design-dimens) */
    const val material_design_dimens: String = "1.4" // up-to-date

    /**
     * [rx-preferences website](https://github.com/f2prateek/rx-preferences) */
    const val rx_preferences: String = "2.0.0" // up-to-date

    /**
     * [compiler website](https://github.com/bumptech/glide) */
    const val com_github_bumptech_glide: String = "4.8.0" // up-to-date

    /**
     * [conductor website](https://github.com/bluelinelabs/Conductor) */
    const val conductor: String = "be8b3c5" // available milestone: "2.1.4" 

    /**
     * [kotson website](https://github.com/SalomonBrys/Kotson) */
    const val kotson: String = "2.5.0" // up-to-date

    /**
     * [smoothie website](https://github.com/stephanenicolas/toothpick.git) */
    const val com_github_stephanenicolas_toothpick: String = "1.1.3" // up-to-date

    /**
     * [material website](http://developer.android.com/tools/extras/support-library.html) */
    const val material: String = "1.0.0" // up-to-date

    /**
     * [flexbox website](https://github.com/google/flexbox-layout) */
    const val flexbox: String = "1.0.0" // available milestone: "1.1.0" 

    /**
     * [gson website](https://github.com/google/gson) */
    const val gson: String = "2.8.5" // up-to-date

    /**
     * [rxbinding-appcompat-v7-kotlin website](https://github.com/JakeWharton/RxBinding/) */
    const val com_jakewharton_rxbinding2: String = "2.1.1" // available milestone: "2.2.0" 

    const val rxrelay: String = "2.1.0" // up-to-date

    /**
     * [timber website](https://github.com/JakeWharton/timber) */
    const val timber: String = "4.7.1" // up-to-date

    /**
     * [mockito-kotlin website](https://github.com/nhaarman/mockito-kotlin) */
    const val mockito_kotlin: String = "1.5.0" // up-to-date

    /**
     * [sqlite website](https://github.com/pushtorefresh/storio) */
    const val sqlite: String = "3.0.0" // up-to-date

    /**
     * [duktape-android website](https://github.com/square/duktape-android) */
    const val duktape_android: String = "1.3.0" // up-to-date

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "3.11.0" // up-to-date

    /**
     * [rxandroid website](https://github.com/ReactiveX/RxAndroid) */
    const val rxandroid: String = "2.1.0" // up-to-date

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "2.2.2" // available milestone: "2.2.3" 

    /**
     * [rxkotlin website](https://github.com/ReactiveX/RxKotlin) */
    const val rxkotlin: String = "2.3.0" // up-to-date

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.5" // up-to-date

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "4.12" // up-to-date

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val org_jetbrains_kotlin: String = "1.2.70" // available milestone: "1.3.0" 

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val org_jetbrains_kotlinx: String = "0.26.1" // available milestone: "1.0.0" 

    /**
     * [jsoup website](https://jsoup.org/) */
    const val jsoup: String = "1.11.3" // up-to-date

    /**
     * [mockito-core website](https://github.com/mockito/mockito) */
    const val mockito_core: String = "2.16.0" // available milestone: "2.23.0" 

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181029034539+0000"

        const val releaseCandidate: String = ""
    }
}
